language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Servers
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - mkdir -p before-deploy
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp vuild/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy *
  - cd ../ && mkdir -p deploy
  - mv before-deploy/before-deploy.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # value in Travis repo setting
    secret_access_key: $AWS_SECRET_KEY # value in Travis repo settings
    bucket: freelec-springboot-build2 # S3 bucket
    region: ca-central-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # value in Travis repo setting
    secret_access_key: $AWS_SECRET_KEY # value in Travis repo setting
    bucket: freelec-springboot-build2 # S3 bucket
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ca-central-1
    wait-until-deployed: true

# Alarm via mail when complete CI process
notifications:
  email:
    recipients:
      - hyewon.dev@gmail.com
