language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Home of Travis CI Servers
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_deploy:
  - zip -r freelec-springboot2-webservice *
  - mkdir -p deploy
  - mv freelec-springboot2-webservice.zip deploy/freelec-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # value in Travis repo setting
    secret_access_key: $AWS_SECRET_KEY # value in Travis repo settings
    bucket: freelec-springboot-build2 # S3 bucket
    region: ca-central-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true
  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: freelec-springboot-build2
    key: freelec-springboot2-webservice.zip
    bundle_type: zip
    application: freelec-springboot2-webservice
    deployment_group: freelec-springboot2-webservice-group
    region: ca-central-1
    wait-until-deployed: true

# Alarm via mail when complete CI process
notifications:
  email:
    recipients:
      - hyewon.dev@gmail.com
